[package]
name = "json-lsp-hz"
version = "0.1.0"
edition = "2021"
author = "shnarazk@github.com"

[dependencies]
dashmap = "6.1"
lsp-types = "^0.97"
ropey = "1.6"
serde = { version = "1.0", features = ["derive"] }
serde_derive = "1.0"
serde_json = "^1.0"
tower-lsp = "^0.20"
tokio = { version = "1", features = ["full"] }
